archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make gen
builds:
  - binary: pulumi-resource-runpod
    dir: pkg
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/runpod/go-sdk/pkg/pulumi-runpod-native/provider/Version={{.Tag }}
    main: ./pulumi-runpod-native/provider/cmd/pulumi-resource-runpod/
changelog:
  skip: true
release:
  disable: false
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
